apiVersion: v2
name: kubevoip
description: A Kubernetes operator for scalable SIP platforms.
type: application
version: 0.6.7
appVersion: 0.6.7
home: https://kubevoip.com
icon: https://raw.githubusercontent.com/kubevoip/kubevoip/main/assets/logo.svg
keywords:
- voip
- asterisk
- sip
- kubernetes
- operator
sources:
- https://github.com/kubevoip/kubevoip
annotations:
  artifacthub.io/category: networking
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: website
      url: https://kubevoip.com
    - name: documentation
      url: https://docs.kubevoip.com
    - name: source
      url: https://github.com/kubevoip/kubevoip
    - name: support
      url: https://github.com/kubevoip/kubevoip/issues
