apiVersion: v2
name: kubevoip
description: A Kubernetes operator for scalable SIP platforms.
type: application
version: 0.6.8
appVersion: 0.6.8
home: https://kubevoip.com
icon: https://raw.githubusercontent.com/kubevoip/kubevoip/main/assets/logo.png
keywords:
- voip
- asterisk
- sip
- kubernetes
- operator
sources:
- https://github.com/kubevoip/kubevoip
annotations:
  artifacthub.io/category: networking
  artifacthub.io/operator: 'true'
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/license: MIT
  artifacthub.io/links: "- name: website\n  url: https://kubevoip.com\n- name: documentation\n\
    \  url: https://docs.kubevoip.com\n- name: source\n  url: https://github.com/kubevoip/kubevoip\n\
    - name: support\n  url: https://github.com/kubevoip/kubevoip/issues\n"
  artifacthub.io/signKey: 'fingerprint: 9C70EA83B762C2C97292207DAD39B317609DC2CE

    url: https://raw.githubusercontent.com/kubevoip/charts/main/keys/kubevoip-chart-signing.asc

    '
